### ISSUE TITLE
ЛР 5, проблемы с кириллицей для пользователей Windows

### ISSUE THREAD

**Issue by ANTONINIK** [mivafoxy/FaN#1]
Для файлов [family.pl](https://github.com/mivafoxy/FaN/blob/main/Prolog/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%965/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/family.pl) и [animals.pl](https://github.com/mivafoxy/FaN/blob/main/Prolog/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%965/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/animals.pl) следует добавить первую строчку `:- encoding(utf8).` 
Это позволит избежать ошибок Syntax error: Operator expected при запуске кода

**Comment by mivafoxy** [comment]
Я добавил на этот счет комментарий в .md файл в папке с Prolog-ом, и так же в примерах эту закомментированную строчку. Спасибо.
